from __future__ import annotations

from app.modules.customers.errors import CustomerNotFoundError, LicenseNotFoundError, PassportNotFoundError
from app.modules.customers.services import (
    create_brazil_license,
    create_customer,
    create_nj_license,
    create_passport,
    delete_brazil_license,
    delete_nj_license,
    delete_passport,
    deactivate_brazil_license,
    deactivate_customer,
    deactivate_nj_license,
    deactivate_passport,
    get_brazil_license_or_404,
    get_customer_or_404,
    get_nj_license_or_404,
    get_passport_or_404,
    list_brazil_licenses,
    list_customers,
    list_nj_licenses,
    list_passports,
    renew_brazil_license,
    renew_nj_license,
    renew_passport,
    update_brazil_license,
    update_customer,
    update_nj_license,
    update_passport,
)

__all__ = [
    "CustomerNotFoundError",
    "LicenseNotFoundError",
    "PassportNotFoundError",
    "create_brazil_license",
    "create_customer",
    "create_nj_license",
    "create_passport",
    "delete_brazil_license",
    "delete_nj_license",
    "delete_passport",
    "deactivate_brazil_license",
    "deactivate_customer",
    "deactivate_nj_license",
    "deactivate_passport",
    "get_brazil_license_or_404",
    "get_customer_or_404",
    "get_nj_license_or_404",
    "get_passport_or_404",
    "list_brazil_licenses",
    "list_customers",
    "list_nj_licenses",
    "list_passports",
    "renew_brazil_license",
    "renew_nj_license",
    "renew_passport",
    "update_brazil_license",
    "update_customer",
    "update_nj_license",
    "update_passport",
]
